[project]
name = "ingress-echo"
version = "0.1.0"
description = "Ingress controller test echo app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.2",
    "uvicorn>=0.38.0",
    "python-multipart>=0.0.9",
]
