{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: {{ .Values.gateway.listener }}
  hostnames:
  {{- range .Values.gateway.hosts }}
    - {{ .host | quote }}
  {{- end }}
  rules:
  {{- range .Values.gateway.hosts }}
  {{- range .paths }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .path }}
      filters:
        {{- if $.Values.gateway.features.redirect.enabled }}
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: {{ $.Values.gateway.features.redirect.statusCode | default 301 }}
        {{- end }}
      backendRefs:
        - name: {{ $.Release.Name }}
          port: {{ $.Values.service.port }}
  {{- end }}
  {{- end }}
{{- end }}