{{- if and (hasKey .Values "ingressRoute") .Values.ingressRoute.enabled (eq .Values.ingress.className "traefik") -}}
{{- $fullName := include "chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  {{- if .Values.ingressRoute.tls }}
  tls:
    {{- toYaml .Values.ingressRoute.tls | nindent 4 }}
  {{- end }}
  routes:
    {{- range .Values.ingressRoute.routes }}
    - match: {{ .match | quote }}
      kind: {{ .kind | default "Rule" }}
      {{- if .middlewares }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ .name }}
          namespace: {{ .namespace | default $.Release.Namespace }}
        {{- end }}
      {{- end }}
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
          {{- if .sticky }}
          sticky:
            cookie:
              name: {{ .sticky.cookie.name }}
              httpOnly: {{ .sticky.cookie.httpOnly }}
              secure: {{ .sticky.cookie.secure }}
              sameSite: {{ .sticky.cookie.sameSite }}
          {{- end }}
    {{- end }}
{{- end }}

